
package com.teamcenter.services.core._2006_03;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Core0603SessionService", targetNamespace = "http://teamcenter.com/Services/Core/2006-03", wsdlLocation = "http://192.168.2.58:7001/tc/services/Core-2006-03-Session?wsdl")
public class Core0603SessionService
    extends Service
{

    private final static URL CORE0603SESSIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException CORE0603SESSIONSERVICE_EXCEPTION;
    private final static QName CORE0603SESSIONSERVICE_QNAME = new QName("http://teamcenter.com/Services/Core/2006-03", "Core0603SessionService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.2.58:7001/tc/services/Core-2006-03-Session?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CORE0603SESSIONSERVICE_WSDL_LOCATION = url;
        CORE0603SESSIONSERVICE_EXCEPTION = e;
    }

    public Core0603SessionService() {
        super(__getWsdlLocation(), CORE0603SESSIONSERVICE_QNAME);
    }

    public Core0603SessionService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CORE0603SESSIONSERVICE_QNAME, features);
    }

    public Core0603SessionService(URL wsdlLocation) {
        super(wsdlLocation, CORE0603SESSIONSERVICE_QNAME);
    }

    public Core0603SessionService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CORE0603SESSIONSERVICE_QNAME, features);
    }

    public Core0603SessionService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Core0603SessionService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Core0603Session
     */
    @WebEndpoint(name = "Core-2006-03-Session")
    public Core0603Session getCore200603Session() {
        return super.getPort(new QName("http://teamcenter.com/Services/Core/2006-03", "Core-2006-03-Session"), Core0603Session.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Core0603Session
     */
    @WebEndpoint(name = "Core-2006-03-Session")
    public Core0603Session getCore200603Session(WebServiceFeature... features) {
        return super.getPort(new QName("http://teamcenter.com/Services/Core/2006-03", "Core-2006-03-Session"), Core0603Session.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CORE0603SESSIONSERVICE_EXCEPTION!= null) {
            throw CORE0603SESSIONSERVICE_EXCEPTION;
        }
        return CORE0603SESSIONSERVICE_WSDL_LOCATION;
    }

}
